### ISSUE TITLE
Most Flatpak icons aren't showing

### ISSUE THREAD

**Issue by mijorus** [fabrialberio/PinApp#1]
I might have a fix for that, but it's a bit hacky

**Comment by mijorus** [comment]
![image](https://user-images.githubusercontent.com/39067225/194942926-5e66e828-0a7c-4188-8110-597172a17677.png)

**Comment by fabrialberio** [comment]
Because of the Flatpak sandbox, the app look for icons only in specific folders. 
Are there any icons in ```/var/lib/flatpak/exports/share/icons```?

**Comment by mijorus** [comment]
I addressed this while working on Boutique, take a look at this:

https://github.com/mijorus/PinApp/tree/icon-fix

**Comment by mijorus** [comment]
> Because of the Flatpak sandbox, the app look for icons only in specific folders. Are there any icons in `/var/lib/flatpak/exports/share/icons`?

These are system wide apps, they are showing up correctly indeed

**Comment by fabrialberio** [comment]
Ok, so the idea is to get icons from appstream cache.
That is a cool concept, I'll think about how to implement it in a more versatile way.

**Comment by mijorus** [comment]
I've been fighting with the exact same problem on my side-project "boutique", after days of work reading from the cache was the only solution I found; btw:

- Distro: PopOS 22.04, Gnome 42
- No custom themes, no custom icons, everything is stock.

**Comment by mijorus** [comment]
> * Getting icons from the appstream folder allows you to use icons from applications that are not installed, which would be visible inside the app but not in the system applications list.

Yes, but you can check if a `.desktop` file exists before reading the cache.

> * It doesn't seem to 100% solve the bug you're facing: from the screenshots I can see that some system application icons (e.g. Geoclue demo agent) are still missing, because the apps they belong to are not on flathub.

This program if not a flatpak, it's some system link which is supposed to be hidden on gnome anyway:

```
[Desktop Entry]
Name=Geoclue Demo agent
GenericName=Demo geoclue agent
Keywords=geolocation;
Exec=/usr/libexec/geoclue-2.0/demos/agent
Icon=mark-location-symbolic
NotShowIn=GNOME;
NoDisplay=true
Terminal=false
Type=Application
```

**Comment by fabrialberio** [comment]
After testing with Pop OS it seems that at least part of the problem is with the icon theme used by the system; changing it to Adwaita makes all non-flatpak icons reappear (including Geoclue's)
Still, I have no idea about Flatpak apps: the icons are where the app expects them to be, they just don't get loaded.

**Comment by fabrialberio** [comment]
d92a319 should fix your issue. It was a problem with Gtk not searching for icons in the user's flatpak folder

**Comment by mijorus** [comment]
I can confirm , fixed
