### ISSUE TITLE
[Request]: Add support for snap apps

### ISSUE THREAD

**Issue by thatLeaflet** [fabrialberio/PinApp#26]
**Is your feature request related to a problem? Please describe.**
While I generally prefer flatpak apps, there are a few apps that work better as snaps. Two that come to mind are Bitwarden (since it's an official package) and VSCode (official package and works much better as an IDE since its unsandboxed). However, PinApp doesn't seem to be able to recognize that these apps are installed and create new desktop entries for them.

**Describe the solution you'd like**
I would like for PinApp to identify these apps. These are both Electron apps that still use XWayland, I would like to be able to use PinApp to add necessary launch flags to tell them to use Wayland instead.

**Comment by fabrialberio** [comment]
I have added snap support with [7c826f8](https://github.com/fabrialberio/PinApp/commit/7c826f8c16e059d0bbe52cc88dd5120fbc2df594), enjoy!
