### ISSUE TITLE
[Bug]: Issues with Flatpak manifest

### ISSUE THREAD

**Issue by suwermave** [fabrialberio/PinApp#31]
Flathub thinks that source is proprietary when, in fact, it's distributed for free in GPL in this repository.

**Comment by fabrialberio** [comment]
Flathub rightfully specifies the code is auditable.
The app is reported as unsafe because to modify desktop entries it must access some non-standard filesystem locations.

![immagine](https://github.com/fabrialberio/PinApp/assets/88488692/707853e7-c949-44d9-ae41-8ec2ccf3cc6c)
