### ISSUE TITLE
Appdata summary is too long

### ISSUE THREAD

**Issue by bertob** [fabrialberio/PinApp#39]
The [appdata guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/) recommend a maximum length of 35 characters for the summary, the current one (`Create and edit application shortcuts`) is a bit longer than that. How about e.g. `Create and edit app launchers` instead?

**Comment by fabrialberio** [comment]
Fixed in [f5c3814](https://github.com/fabrialberio/PinApp/commit/f5c381441737790cb552a8f35f9b0af7436ac986) by shortening "application" to "app".

I didn't launchers" because although
