### ISSUE TITLE
[Request]: Make UI translatable

### ISSUE THREAD

**Issue by rene-coty** [fabrialberio/PinApp#4]
Hi !
Thanks for your work !
I'd like to contribute by translating the app UI, but a .pot file is needed in the /po folder...

**Comment by fabrialberio** [comment]
That would be great!
I'm working on it

**Comment by fabrialberio** [comment]
I've configured ui translation and added a .pot file. I've also added an Italian translation, if you need an example.

**Comment by rene-coty** [comment]
Ok, I will create a French translation soon
