### ISSUE TITLE
Read from /run/host/usr/share/applications in flatpak package when host filesystem is exposed

### ISSUE THREAD

**Issue by RushingAlien** [fabrialberio/PinApp#5]
**Is your feature request related to a problem? Please describe.**
Hi! loving the app, but one problem, the flatpak package doesn't read all desktop entries, even with host or /usr/share/applications exposed (these should be mounted at /run/host/ in the container

**Describe the solution you'd like**
For PinApp flatpak package to read from host mount point

**Describe alternatives you've considered**
Install PinApp as non-Flatpak.

**Comment by fabrialberio** [comment]
I didn't know you could do that, thanks! Implemented in [3e99010](https://github.com/fabrialberio/PinApp/commit/3e99010c55effd117b557289dfa4a03dd15d85da).

**Comment by RushingAlien** [comment]
Dope, thank you so much

**Comment by LSeelig** [comment]
I have the flatpak, and pinapp doesn't see apps here.
