### ISSUE TITLE
[Bug]: Missing UI icons

### ISSUE THREAD

**Issue by mijorus** [fabrialberio/PinApp#6]
### Describe the bug
Missing icons in the UI

 ### To Reproduce
1. Install PopOS 22.04
2. Open PinApp

### Screenshots
see below

### Linux distribution
PopOS 22.04, everything stock (icon theme, shell theme etc...)

### Additional context
I would suggest you to ship these icons in directly your bundle

![image](https://user-images.githubusercontent.com/39067225/196132728-10756476-7dfc-4f96-9eb5-4090831f5b18.png)

**Comment by fabrialberio** [comment]
The solution is to change the icon theme to Adwaita using Gnome Tweaks.
The issue is with the Pop OS default icon theme, not with the app itself, therefore it's not my job to fix it.

**Comment by mijorus** [comment]
I mean,,,, really? 
Pop OS is one of the most popular distro out there.

What does it take it fix it? It's just a matter of bundling an SVG in the package.

The Linux ecosystem is a mess, if you are not aware of it.

**Comment by fabrialberio** [comment]
Sorry, my answer was kinda rude.
I don't think bundling every icon used in the app is a great solution, and I would also prefer to avoid to bundle the whole of Libadwaita.
I can't think of a better solution right now, but I'll do some testing.

**Comment by mijorus** [comment]
to be clear, nobody here is expecting you to fix an issue today, nor tomorrow or next week; but saying you don't give mind to a problem that afflicts one of the most popular distribution and that takes minutes to fix, seems a bit too much IMO

Btw, you could just have left the issue open.

**Comment by fabrialberio** [comment]
I've tested it on a new install of Pop OS and all icons show up properly, even with the default Pop icon theme.
Something must have changed since I last tested the issue, an whatever it was it has apparently fixed it.
