### ISSUE TITLE
[Bug]: App interaction is slow

### ISSUE THREAD

**Issue by realgrm** [fabrialberio/PinApp#8]
### Describe the bug
Every interaction with the app is slow with constant stuttering. 

 ### To Reproduce
1. Open app
2. Scroll down
3. Or change tab

### Linux distribution
Fedora Linux 37.1.2 (Silverblue)
flatpak-1.14.0-2.fc37.x86_64
io.github.fabrialberio.pinapp/x86_64/stable  1.1.5
Tested with a new system user (default configurations).

### Additional context

terminal output
```
$ io.github.fabrialberio.pinapp

flatpak
Traceback (most recent call last):
  File "/app/share/PinApp/pinapp/file_page.py", line 146, in <lambda>
    self.banner_squeezer.connect('notify', lambda *_: self._update_app_banner())
  File "/app/share/PinApp/pinapp/file_page.py", line 282, in _update_app_banner
    app_name_row = StringRow(self.file.appsection.Name)
AttributeError: 'NoneType' object has no attribute 'appsection'
Gsk-Message: 22:32:52.103: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkWaylandToplevel': Failed to create EGL display

```

**Comment by fabrialberio** [comment]
I've tested this in a Fedora Silverblue 37 VM, but could not replicate the issue.

Does this happen with other libadwaita applications?
What version of opengl are you using? You can get it by running `glxinfo | grep "OpenGL version"`.

Try running it with the environment variable `GDK_GL=gles`, that should force Gdk to use the OpenGL ES implementation and might fix the issue.

**Comment by realgrm** [comment]
Hi, sorry for the hiatus. Well, the issue does not occur anymore. Closing the issue
